/**
 * Helios | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CentreModule } from './centreModule';


export interface UserInfo { 
    id?: number;
    email?: string | null;
    nom?: string | null;
    prenom?: string | null;
    isConnected?: boolean;
    centreModules?: Array<CentreModule> | null;
    sysAdminModules?: Array<any> | null;
    adminModules?: Array<any> | null;
    typeMembre?: number | null;
}

