/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Aspects } from './aspects';
import { Utilisateur } from './utilisateur';
import { Activitee } from './activitee';


export interface Aspect { 
    id?: number;
    creation?: string;
    modification?: string | null;
    code: Aspects;
    description?: string | null;
    utilisateurs?: Array<Utilisateur> | null;
    activitees?: Array<Activitee> | null;
}
export namespace Aspect {
}


