/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Aspects = 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900;

export const Aspects = {
    NUMBER_100: 100 as Aspects,
    NUMBER_200: 200 as Aspects,
    NUMBER_300: 300 as Aspects,
    NUMBER_400: 400 as Aspects,
    NUMBER_500: 500 as Aspects,
    NUMBER_600: 600 as Aspects,
    NUMBER_700: 700 as Aspects,
    NUMBER_800: 800 as Aspects,
    NUMBER_900: 900 as Aspects
};

