/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateEmailCampaignSender } from './createEmailCampaignSender';


export interface CampaignRequest { 
    name: string | null;
    subject: string | null;
    mails: Array<string> | null;
    htmlContent: string | null;
    sender: CreateEmailCampaignSender;
    params?: any | null;
}

