/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CentreCampaignRequest } from './centreCampaignRequest';
import { CreateEmailCampaignSender } from './createEmailCampaignSender';


export interface CampaignRequest { 
    name: string | null;
    subject: string | null;
    htmlContent: string | null;
    delay?: number | null;
    sender: CreateEmailCampaignSender;
    params?: any | null;
    centreRequest?: Array<CentreCampaignRequest> | null;
    listIds?: Array<number> | null;
    scheduledAt?: string | null;
}

