/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypeCentre } from './typeCentre';
import { Utilisateur } from './utilisateur';
import { Activitee } from './activitee';


export interface Centre { 
    id?: number;
    creation?: string;
    modification?: string | null;
    code: string | null;
    typeCentre: TypeCentre;
    libelle: string | null;
    description?: string | null;
    adresse?: string | null;
    codePostal?: string | null;
    ville?: string | null;
    pays?: string | null;
    capacite?: number | null;
    utilisateurs?: Array<Utilisateur> | null;
    activites?: Array<Activitee> | null;
}

