/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CentreInfo } from './centreInfo';


export interface ConferenceInfo { 
    libelle?: string | null;
    dateDebut?: string | null;
    dateFin?: string | null;
    description?: string | null;
    typeActivitee?: string | null;
    centre?: CentreInfo;
    isRegistered?: boolean;
}

