/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Droits = 100 | 200 | 300;

export const Droits = {
    NUMBER_100: 100 as Droits,
    NUMBER_200: 200 as Droits,
    NUMBER_300: 300 as Droits
};

