/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Droits } from './droits';
import { Centre } from './centre';
import { Module } from './module';
import { Utilisateur } from './utilisateur';


export interface Droit { 
    id?: number;
    description?: string | null;
    code?: Droits;
    creation?: string;
    modification?: string | null;
    utilisateur: Utilisateur;
    centre?: Centre;
    module?: Module;
}
export namespace Droit {
}


