/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Civilite } from './civilite';
import { TypeMembre } from './typeMembre';
import { Centre } from './centre';
import { Utilisateur } from './utilisateur';


export interface Membre { 
    id?: number;
    creation?: string;
    modification?: string | null;
    civilite: Civilite;
    nom: string | null;
    prenom: string | null;
    typeMembre: TypeMembre;
    centre?: Centre;
    email?: string | null;
    profession?: string | null;
    telephone?: string | null;
    adresse?: string | null;
    codePostal?: string | null;
    ville?: string | null;
    pays?: string | null;
    emailValide?: boolean;
    connaissances?: string | null;
    commentaires?: string | null;
    dateNaissance?: string;
    utilisateur?: Utilisateur;
    parents?: Array<Membre> | null;
    enfants?: Array<Membre> | null;
}

