/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Modules = 'Accueil' | 'Conferences' | 'ConferencesInscriptions' | 'ConferencesUserInscriptions' | 'Registre' | 'RegistreFicheEleves' | 'Comptabilite' | 'Administation' | 'Developpement';

export const Modules = {
    Accueil: 'Accueil' as Modules,
    Conferences: 'Conferences' as Modules,
    ConferencesInscriptions: 'ConferencesInscriptions' as Modules,
    ConferencesUserInscriptions: 'ConferencesUserInscriptions' as Modules,
    Registre: 'Registre' as Modules,
    RegistreFicheEleves: 'RegistreFicheEleves' as Modules,
    Comptabilite: 'Comptabilite' as Modules,
    Administation: 'Administation' as Modules,
    Developpement: 'Developpement' as Modules
};

