/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Modules = 1000 | 2000 | 2100 | 2200 | 3000 | 4000;

export const Modules = {
    NUMBER_1000: 1000 as Modules,
    NUMBER_2000: 2000 as Modules,
    NUMBER_2100: 2100 as Modules,
    NUMBER_2200: 2200 as Modules,
    NUMBER_3000: 3000 as Modules,
    NUMBER_4000: 4000 as Modules
};

