/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Modules } from './modules';


export interface Module { 
    id?: number;
    description?: string | null;
    code?: Modules;
    creation?: string;
    modification?: string | null;
    label: string | null;
    path: string | null;
    parentId?: number | null;
    sousMenus?: Array<Module> | null;
    icon?: string | null;
    title?: string | null;
    prefixIcon?: string | null;
    suffixIcon?: string | null;
    isPublic?: boolean;
}
export namespace Module {
}


