/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Roles = 'SYSADMIN' | 'ADMIN_FULL_ACCESS' | 'USER_MANAGER';

export const Roles = {
    Sysadmin: 'SYSADMIN' as Roles,
    AdminFullAccess: 'ADMIN_FULL_ACCESS' as Roles,
    UserManager: 'USER_MANAGER' as Roles
};

