/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Roles } from './roles';
import { Utilisateur } from './utilisateur';


export interface Role { 
    id?: number;
    creation?: string;
    modification?: string | null;
    code: Roles;
    utilisateurs?: Array<Utilisateur> | null;
}
export namespace Role {
}


