/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Roles = 100 | 200 | 300;

export const Roles = {
    NUMBER_100: 100 as Roles,
    NUMBER_200: 200 as Roles,
    NUMBER_300: 300 as Roles
};

