/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatutsMembres = 'Present' | 'Suivi' | 'Absent' | 'Demissionnaire' | 'Decede';

export const StatutsMembres = {
    Present: 'Present' as StatutsMembres,
    Suivi: 'Suivi' as StatutsMembres,
    Absent: 'Absent' as StatutsMembres,
    Demissionnaire: 'Demissionnaire' as StatutsMembres,
    Decede: 'Decede' as StatutsMembres
};

