/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TypesActivitees = 'ServiceTempleInteresse' | 'ServiceApprofondissement' | 'WeekEndVille' | 'ConferenceRenouvellement' | 'ConferenceECS' | 'ConferenceECC' | 'ConferenceECS_ECC' | 'ConventGraalCTO';

export const TypesActivitees = {
    ServiceTempleInteresse: 'ServiceTempleInteresse' as TypesActivitees,
    ServiceApprofondissement: 'ServiceApprofondissement' as TypesActivitees,
    WeekEndVille: 'WeekEndVille' as TypesActivitees,
    ConferenceRenouvellement: 'ConferenceRenouvellement' as TypesActivitees,
    ConferenceEcs: 'ConferenceECS' as TypesActivitees,
    ConferenceEcc: 'ConferenceECC' as TypesActivitees,
    ConferenceEcsEcc: 'ConferenceECS_ECC' as TypesActivitees,
    ConventGraalCto: 'ConventGraalCTO' as TypesActivitees
};

