/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypesActivitees } from './typesActivitees';
import { Activitee } from './activitee';


export interface TypeActivitee { 
    id?: number;
    creation?: string;
    modification?: string | null;
    code: TypesActivitees;
    description?: string | null;
    activites?: Array<Activitee> | null;
}
export namespace TypeActivitee {
}


