/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TypesMembres = 100 | 200 | 300 | 400 | 500 | 600 | 700 | 800 | 900 | 1000;

export const TypesMembres = {
    NUMBER_100: 100 as TypesMembres,
    NUMBER_200: 200 as TypesMembres,
    NUMBER_300: 300 as TypesMembres,
    NUMBER_400: 400 as TypesMembres,
    NUMBER_500: 500 as TypesMembres,
    NUMBER_600: 600 as TypesMembres,
    NUMBER_700: 700 as TypesMembres,
    NUMBER_800: 800 as TypesMembres,
    NUMBER_900: 900 as TypesMembres,
    NUMBER_1000: 1000 as TypesMembres
};

