/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { Membre } from './membre';
import { Droit } from './droit';


export interface Utilisateur { 
    id?: number;
    creation?: string;
    modification?: string | null;
    email: string | null;
    membre?: Membre;
    membreId?: number | null;
    droits?: Array<Droit> | null;
    roles?: Array<Role> | null;
}

