/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Civilites = 'Monsieur' | 'Madame';

export const Civilites = {
    Monsieur: 'Monsieur' as Civilites,
    Madame: 'Madame' as Civilites
};

