/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Civilites } from './civilites';


export interface Civilite { 
    id?: number;
    creation?: string;
    modification?: string | null;
    code: Civilites;
    description?: string | null;
}
export namespace Civilite {
}


