/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Droits = 'PUBLIC' | 'LECTURE' | 'AJOUT' | 'MODIFICATION';

export const Droits = {
    Public: 'PUBLIC' as Droits,
    Lecture: 'LECTURE' as Droits,
    Ajout: 'AJOUT' as Droits,
    Modification: 'MODIFICATION' as Droits
};

