/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Utilisateur } from './utilisateur';
import { Activitee } from './activitee';


export interface Inscription { 
    id?: number;
    creation?: string;
    modification?: string | null;
    utilisateur?: Utilisateur;
    utilisateurId?: number | null;
    activitee?: Activitee;
    activiteeId?: number | null;
    infos?: string | null;
}

