/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypesMembres } from './typesMembres';


export interface MemberFilter { 
    nom?: string | null;
    prenom?: string | null;
    email?: string | null;
    ville?: string | null;
    pays?: string | null;
    centre?: string | null;
    aspect?: string | null;
    l_villes?: Array<string> | null;
    l_pays?: Array<string> | null;
    l_centres?: Array<string> | null;
    l_aspects?: Array<TypesMembres> | null;
}

