/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TypesActivitees } from './typesActivitees';
import { TypesMembres } from './typesMembres';


export interface RegisterConferenceRequest { 
    centreId: number;
    codeTypeActivitee: TypesActivitees;
    libelle: string | null;
    description?: string | null;
    dateDebut: string;
    dateFin: string;
    typeMembres: Array<TypesMembres> | null;
}
export namespace RegisterConferenceRequest {
}


