/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Membre } from './membre';
import { StatutsMembres } from './statutsMembres';


export interface StatutMembre { 
    id?: number;
    description?: string | null;
    code?: StatutsMembres;
    creation?: string;
    modification?: string | null;
    membres?: Array<Membre> | null;
}
export namespace StatutMembre {
}


