/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TypesMembres = 'PremierAspect' | 'DeuxiemeAspect' | 'ECS' | 'ECCLESIA' | 'GRAAL' | 'CinquiemeAspect' | 'SixiemeAspect' | 'SeptiemeAspect' | 'Interesse' | 'Jeunesse';

export const TypesMembres = {
    PremierAspect: 'PremierAspect' as TypesMembres,
    DeuxiemeAspect: 'DeuxiemeAspect' as TypesMembres,
    Ecs: 'ECS' as TypesMembres,
    Ecclesia: 'ECCLESIA' as TypesMembres,
    Graal: 'GRAAL' as TypesMembres,
    CinquiemeAspect: 'CinquiemeAspect' as TypesMembres,
    SixiemeAspect: 'SixiemeAspect' as TypesMembres,
    SeptiemeAspect: 'SeptiemeAspect' as TypesMembres,
    Interesse: 'Interesse' as TypesMembres,
    Jeunesse: 'Jeunesse' as TypesMembres
};

