/**
 * osmose-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Membre } from './membre';
import { TypesMembres } from './typesMembres';
import { Activitee } from './activitee';


export interface TypeMembre { 
    id?: number;
    description?: string | null;
    code?: TypesMembres;
    creation?: string;
    modification?: string | null;
    membres?: Array<Membre> | null;
    activitees?: Array<Activitee> | null;
}
export namespace TypeMembre {
}


