name: Deploy
# Trigger on push to the default branch or on pull requests to the default branch
on:
  push:
    branches: main
  pull_request:
    branches: main
  # Add a manual trigger (we'll discuss the options below)
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t intranet-rco:latest .
      - name: Move compose to home
        run: mv docker-compose.yml $HOME/intranet-rco/docker-compose.yml
      - name: Deploy
        run: cd $HOME/intranet-rco && docker-compose up -d       
        env:
          ANGULAR_ENVIRONMENT: production
